chore(website): update vite config format
```
(!) Your Vite config uses features that are unsupported by `configLoader: 'native'`, which is planned to become the default in a future major version of Vite:
  - import "./plugin/git_info" without a file extension (vite.config.ts:4:25). Add the file extension
  - import "./plugin/load_files" without a file extension (vite.config.ts:5:27). Add the file extension
```

```
vite.config.ts:4:25 - error TS5097: An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled.
```